# Numpy Refresher

### Basics

In [20]:
import numpy as np

In [26]:
val_list = [[1.4, 3.22, 45.3],
            [4.5, 42.1, 1.11]]
arr_1 = np.array(val_list)
arr_1

array([[ 1.4 ,  3.22, 45.3 ],
       [ 4.5 , 42.1 ,  1.11]])

In [29]:
print(arr_1.dtype)
print(arr_1.astype(np.float32).dtype) # automatically infers array float type as float64 else can be overriden with intended data type.


float64
float32


In [30]:
arr_1.shape

(2, 3)

In [39]:
scalar = arr_1[0,1] 
scalar

3.22

### Array Construction routines


In [41]:
# Arrays don't support generators directly. 
def generator():
    for i in range(5):
        if i % 2:
            yield i

In [42]:
my_gen = generator()

In [43]:
np.fromiter(my_gen, dtype=int)

array([1, 3])

In [46]:
# Prefill with '0's and '1's
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [48]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
# Range


In [52]:
np.arange(1.0, 21.0, 3) 

array([ 1.,  4.,  7., 10., 13., 16., 19.])

In [53]:
np.linspace(2., 4, num=10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

### Array Indexing


In [72]:
ay = np.arange(3, 45, 3)
ay2d = np.array([[1, 2, 3],[4, 5, 6]])
ay2d

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
ay[2]

9

In [65]:
ay[0:2]

array([3, 6])

In [67]:
ay2d[-1, -2]

5

In [68]:
ay2d[-2, 1]

2

In [71]:
ay2d[0] # First row

array([1, 2, 3])

In [73]:
ay2d[:,0] # First col

array([1, 4])

In [79]:
ay2d[:, :2] # First 2 columns

array([[1, 2],
       [4, 5]])

In [85]:
ay2d[:,1:2] # Centre column

array([[2],
       [5]])

In [88]:
ay2d[1:2, :] # Second Row 2D Array

array([[4, 5, 6]])

In [90]:
ay2d[1, :] # Second Row 1D Array

array([4, 5, 6])

### Array Math and Universal Functions

In [91]:
ay2d

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
# List way
np.array([row * 3 for row in ay2d])

array([[ 3,  6,  9],
       [12, 15, 18]])

In [99]:
np.array([[ val * 5 for val in row] for row in ay2d])

array([[ 5, 10, 15],
       [20, 25, 30]])

In [97]:
# Numpy array way

In [102]:
sq2d = ay2d ** 2 
sq2d

array([[ 1,  4,  9],
       [16, 25, 36]])

In [104]:
np.sqrt(sq2d)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [107]:
# Sum or prod along the axis
np.add.reduce(ay2d, axis=1) # column sums

array([ 6, 15])

In [111]:
ay2d.prod(axis =0)

array([ 4, 10, 18])

In [113]:
ay2d.sum() # sum on the whole array

21

In [115]:
ay2d.argmax() # returns index of the max element

5

In [118]:
ay2d.var() # variance of the array

2.9166666666666665

In [119]:
ay2d.std() # standard deviation

1.707825127659933

### Broadcasting